ARG STACTOOLS_VERSION=latest
FROM ghcr.io/stac-utils/stactools:${STACTOOLS_VERSION}-dev

WORKDIR /opt/stactools-jrc-gsw

# For caching purposes, install dependencies but remove the actual package
COPY pyproject.toml requirements-dev.txt setup.cfg ./
COPY src/stactools/jrc_gsw/__init__.py src/stactools/jrc_gsw/
RUN pip install -r requirements-dev.txt \
    && pip install . \
    && rm -r /opt/conda/lib/python3.9/site-packages/stactools/jrc_gsw

COPY . ./
RUN pip install -e .
